import json
import sys

files = ['dex_in.json']

if len(sys.argv) > 1:
    files = sys.argv[1:]


def dex_processer(txt_out):
    for file in files:
        with open(file) as json_file:
            data = json.load(json_file)

        for i in data['Dex'][0]['Main']:
            exp = i['I']
            frame_time = i['F'] / 2 # since 60fps / 2 = 30fps

            if exp == 21:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

            if exp == 10:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0.5 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

            if exp == 37:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

            if exp == 36:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

            if exp == 20:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

            if exp == 5:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {0.5 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

            if exp == 15:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

            if exp == 19:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0.5 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {1 * i['V']}\n")

            if exp == 11:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {1 * i['V']}\n")

            if exp == 12:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0.25 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {1 * i['V']}\n")

            if exp == 7:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0.5 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

            if exp == 8:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

            if exp == 17:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0.5 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

            if exp == 39:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0.25 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

            if exp == 18:
                txt_out.write(f"BLINK, {frame_time}, {0.5 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

            if exp == 16:
                txt_out.write(f"BLINK, {frame_time}, {0.6 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

            if exp == 34:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0.1 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

            if exp == 0:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

            if exp == 6:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

            if exp == 1:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

            if exp == 41:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

            if exp == 35:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

            if exp == 38:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0.25 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

            if exp == 3:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

            if exp == 40:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

            if exp == 13:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {0.75 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

            if exp == 9:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {0.75 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

            if exp == 42:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {1 * i['V']}\n")

            if exp == 45:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {1 * i['V']}\n")

            if exp == 44:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

            if exp == 2:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

            if exp == 49:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

            if exp == 51:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0.15 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

            if exp == 52:
                txt_out.write(f"BLINK, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

            if exp == 53:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0.15 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")


            if exp == 54:
                txt_out.write(f"BLINK, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

            if exp == 55:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

            if exp == 56:
                txt_out.write(f"BLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0.25 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

            if exp == 57:
                txt_out.write(f"BLINK, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")

        for i in data['Dex'][0]['Eyes']:
            exp = i['I']
            frame_time = i['F'] / 2 # since 60fps / 2 = 30fps

            if exp == 3:
                txt_out.write(f"BLINK, {frame_time}, {1 * i['V']}\n")
                txt_out.write(f"WINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"WINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SBLINK, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SWINKR, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_BLINKF, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"><, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SUPRISED, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOUBTFUL, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SHARPEYES, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DOWN, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_UP, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"DEX_ANGRY, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SERIOUS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"SADNESS, {frame_time}, {0 * i['V']}\n")
                txt_out.write(f"CHEERFUL, {frame_time}, {0 * i['V']}\n")
        
        txt_out.close()

